version: 2
services:
   web:
      image: nginx:latest
      ports:
         - "81:81"
      volumes:
         - /var/www/experiment/web:/app/web
         - /var/www/experiment/web/logs:/app/log/nginx
         #- ./nginx.conf:/etc/nginx/nginx.conf
         #- ./conf.d:/etc/nginx/conf.d
         #- ./gzip.conf:/etc/nginx/gzip.conf
         #- ./php7-fpm.conf:/etc/nginx/php7-fpm.conf
